const fortunes = [
    "You're as bright as a black hole, and twice as dense.",
    "You bring everyone so much joy when you leave the room.",
    "I'd agree with you, but then we'd both be wrong.",
    "You're not stupid; you just have bad luck thinking.",
    "You're proof that even evolution can go in reverse.",
    "I'd explain it to you, but I left my crayons at home.",
    "You have an entire life to be an idiot. Why not take today off?",
    "You're as useful as a screen door on a submarine.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "If I wanted to hear from an idiot, I'd call you.",
    "You have the perfect face for radio.",
    "You're living proof that even evolution can go in reverse.",
    "I'd agree with you but then we'd both be wrong.",
    "You're as useful as the 'ueue' in 'queue'.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "You're as sharp as a marble.",
    "If brains were dynamite, you wouldn't have enough to blow your nose.",
    "You're as useful as a pogo stick in quicksand.",
    "You're the reason they put instructions on shampoo bottles.",
    "You're proof that God has a sense of humor.",
    "You have the perfect face for radio.",
    "You're as useful as a one-legged man in a butt-kicking contest.",
    "You have a great sense of humor. I hope it's improved by now.",
    "You're like a battery with no charge.",
    "You're the human equivalent of a participation trophy.",
    "You're like a broken pencil - pointless.",
    "You're about as helpful as a broken stoplight in rush hour.",
    "You're like a phone with no signal - lost and disconnected.",
    "You're like a car without an engine - going nowhere fast.",
    "You're like a joke without a punchline.",
    "You're like a chocolate teapot - nice idea, but utterly useless.",
    "You're like a wet match - never going to light up.",
    "You're like a TV with no channels - just static.",
    "You're like a GPS with no signal - completely lost.",
    "You're like a calendar with no dates - pointless.",
    "You're like a car with no wheels - stuck in one place.",
    "You're as useful as an ashtray on a motorcycle.",
    "You're as bright as a small appliance bulb.",
    "Your brain's like a web browser with 50 tabs open - 49 are frozen and the last one is playing music you can't find.",
    "You have the intelligence of a root vegetable.",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "Your mind is like a steel trap - rusty and illegal in 37 states.",
    "You're not the dumbest person on the planet, but you sure better hope they don't die.",
    "You have the charm and charisma of a damp rag.",
    "You're as useful as a chocolate fireguard.",
    "You're as sharp as a beach ball.",
    "You have a great face for wallpaper.",
    "You're like a lighthouse in the middle of a desert - pointless and out of place.",
    "You're as useful as a screen door on a submarine.",
    "You have a mind like a steel trap - anything that goes in gets mangled and dies.",
    "Your mind is like a steel trap - always closed.",
    "You're as bright as a broken light bulb.",
    "You're as swift as a three-toed sloth on tranquilizers.",
    "You're as sharp as a mashed potato.",
    "You have the personality of a dial tone.",
    "You're as welcome as a skunk at a lawn party.",
    "You're as smooth as sandpaper.",
    "You're as pleasant as a blister on a summer day.",
    "You have the wit of a houseplant.",
    "You're as helpful as a backseat driver.",
    "You're as clear as mud.",
    "You have the grace of a reversing dump truck.",
    "You're about as useful as a knitted condom.",
    "You're as clever as a rock.",
    "You have the fashion sense of a scarecrow.",
    "You're as entertaining as watching paint dry.",
    "You're as subtle as a sledgehammer.",
    "You have the charm of a traffic cone.",
    "You're as stable as a Jenga tower.",
    "You're as wise as a toddler with a crayon.",
    "You have the patience of a squirrel on caffeine.",
    "You're about as useful as a one-man band in a marching competition.",
    "You have the grace of a walrus on roller skates.",
    "You're as warm as an iceberg.",
    "You have the personality of a soggy toast.",
    "You're as coordinated as a drunk cat.",
    "You have the enthusiasm of a snail on a salt shaker.",
    "You're about as useful as a chocolate teapot."
];

function generateFortune() {
    const randomIndex = Math.floor(Math.random() * fortunes.length);
    const selectedFortune = fortunes[randomIndex];
    document.getElementById("fortune").textContent = selectedFortune;
}

